// Lightweight offline-prototype browser check; no product build or Provider calls.
const fs=require('fs'),path=require('path'),os=require('os'),cp=require('child_process'),assert=require('assert'),WebSocket=require('/home/isp/wsps/cyf/web/node_modules/ws');
const root=__dirname;
const profile=fs.mkdtempSync('/var/tmp/cyf-prototype-chromium-');const downloads=path.join(profile,'downloads');fs.mkdirSync(downloads);
const child=cp.spawn('/usr/bin/chromium-browser',['--headless','--no-sandbox','--disable-gpu','--no-first-run','--no-default-browser-check','--disable-background-networking','--disable-component-update','--disable-sync','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{stdio:['ignore','ignore','pipe']});
const delay=ms=>new Promise(r=>setTimeout(r,ms));let ws,id=0;const pending=new Map(),errors=[],checks=[],layouts=[];const mark=(name,details)=>checks.push({name,pass:true,details});
async function call(method,params={}){const n=++id;return new Promise((resolve,reject)=>{pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));});}
async function evalJS(expression){const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true,userGesture:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;}
async function click(selector){await evalJS(`(()=>{const x=document.querySelector(${JSON.stringify(selector)});if(!x)throw Error('missing '+${JSON.stringify(selector)});x.click();return true})()`);await delay(65);}
async function viewport(w,h){await call('Emulation.setDeviceMetricsOverride',{width:w,height:h,deviceScaleFactor:1,mobile:w<721});}
async function navigate(page){await evalJS(`go(${JSON.stringify(page)})`);await delay(100);}
async function capture(name){await delay(100);const shot=await call('Page.captureScreenshot',{format:'png',fromSurface:true});fs.writeFileSync(path.join(root,'screenshots',name+'.png'),Buffer.from(shot.data,'base64'));}
(async()=>{let port;for(let i=0;i<150;i++){if(fs.existsSync(path.join(profile,'DevToolsActivePort'))){port=fs.readFileSync(path.join(profile,'DevToolsActivePort'),'utf8').split('\n')[0];break;}await delay(100);}const targets=await fetch('http://127.0.0.1:'+port+'/json').then(r=>r.json());ws=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.once('open',r));ws.on('message',data=>{const x=JSON.parse(data);if(x.id&&pending.has(x.id)){const p=pending.get(x.id);pending.delete(x.id);x.error?p.reject(Error(JSON.stringify(x.error))):p.resolve(x.result);}if(x.method==='Runtime.exceptionThrown')errors.push(x.params.exceptionDetails.text);});await call('Runtime.enable');await call('Page.enable');await call('Network.enable');await call('Network.setBlockedURLs',{urls:['https://*']});await viewport(1440,1000);await call('Page.navigate',{url:(process.env.PROTOTYPE_ORIGIN||'http://127.0.0.1:35111')+'/adjusted/index.html'});await delay(700);

async function type(selector,value){await evalJS(`(()=>{const t=document.querySelector(${JSON.stringify(selector)});t.value=${JSON.stringify(value)};t.dispatchEvent(new Event('input',{bubbles:true}));})()`);}
async function change(selector,checked){await evalJS(`(()=>{const t=document.querySelector(${JSON.stringify(selector)});t.checked=${checked};t.dispatchEvent(new Event('change',{bubbles:true}));})()`);}
async function nativeClick(selector){const r=await evalJS(`(()=>{let e=document.querySelector(${JSON.stringify(selector)});e.scrollIntoView({block:'center'});let r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`);await call('Input.dispatchMouseEvent',{type:'mousePressed',...r,button:'left',clickCount:1});await call('Input.dispatchMouseEvent',{type:'mouseReleased',...r,button:'left',clickCount:1});await delay(100);}
async function geometry(label){let g=await evalJS(`({width:innerWidth,scroll:document.documentElement.scrollWidth,dialog:document.querySelector('dialog[open]')?.getBoundingClientRect().toJSON(),composer:document.querySelector('.composer-body')?.getBoundingClientRect().toJSON(),bottom:[...document.querySelectorAll('.workbench-mobile-nav button')].filter(e=>e.getBoundingClientRect().width).map(e=>e.textContent.trim()),badImages:[...document.images].filter(e=>e.getBoundingClientRect().width&&!e.naturalWidth).map(e=>e.src)})`);assert(g.scroll<=g.width+1,label+JSON.stringify(g));assert.equal(g.badImages.length,0,JSON.stringify(g));if(g.dialog)assert(g.dialog.x>=0&&g.dialog.right<=g.width+1);layouts.push({label,...g});}
assert.equal(await evalJS('document.querySelectorAll(".quick-reference-open,.composer-execute").length'),0);
await type('.overview-quick-request textarea','画一只鸟');await nativeClick('.quick-material-open');await capture('desktop-materials');await geometry('desktop-materials');
for(const id of ['ref-bird','ref-brief','ref-audio'])await change(`[data-pick="${id}"]`,true);
await click('[data-action=confirm-materials]');assert.equal(await evalJS('state.draftFiles.length'),3);await capture('desktop-home');
await click('[data-action=remove][data-id=ref-audio]');assert.equal(await evalJS('state.draftFiles.length'),2);
await click('.quick-material-open');await change('[data-pick=ref-audio]',true);await click('[data-action=close-dialog]');assert.equal(await evalJS('state.draftFiles.length'),2);mark('Unified multi-type materials; remove and cancel semantics');
await nativeClick('.overview-quick-request button.primary');assert.equal(await evalJS('page'),'agents');await nativeClick('.agent-row');assert(!await evalJS('document.querySelector(".agent-panel").innerText.includes("画一只鸟")'));assert.equal(await evalJS('document.querySelectorAll(".agent-panel .mmd-attachments").length'),0);mark('Roster contains Agent information, not requirement or materials');await capture('desktop-agents');await geometry('desktop-agents');await nativeClick('[data-action=assign]');await delay(800);
assert.equal(await evalJS('state.messages[0].files.length'),2);assert.equal(await evalJS('state.messages[0].text'),'画一只鸟');assert.equal(await evalJS('state.outputs[0].type'),'image');mark('Explicit chosen Agent; automatic requirement and files; direct reply');assert.equal(await evalJS('document.querySelectorAll(".chat-panel .toolbar-actions,.chat-panel .hall-voice-controls,.chat-panel .composer-context").length'),0);assert.equal(await evalJS('document.querySelectorAll(".composer-actions button").length'),2);mark('Chat removes navigation shortcuts; only plus and send in integrated composer');await capture('desktop-chat');await geometry('desktop-chat');
await click('[data-action=preview][data-id=result-1]');await capture('desktop-preview');await click('[data-action=close-dialog]');await click('[data-action=quote][data-id=result-1]');await type('.composer-textarea','把这一稿改成黄色，再附上音频和活动方案，以及文字介绍');await nativeClick('.composer-send');await delay(800);
assert.equal(await evalJS('state.messages[2].quote'),'result-1');assert.equal(await evalJS('state.outputs.length'),5);assert.deepEqual(await evalJS('state.outputs.map(x=>x.type)'),['image','image','audio','document','text']);mark('Quoted revision retained; text,image,audio,document outputs');
await nativeClick('[data-action=composer-more]');await click('[data-action=composer-materials]');await change('[data-pick=ref-audio]',true);await click('[data-action=confirm-materials]');await nativeClick('.composer-send');await delay(800);assert.equal(await evalJS('state.messages[4].files[0]'),'ref-audio');mark('Attachment-only follow-up');
await call('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:downloads});
for(const id of ['result-1','result-3','result-4','result-5'])await evalJS(`download('${id}')`);await delay(700);const downloaded=fs.readdirSync(downloads);assert(downloaded.length>=4,downloaded.join(','));for(const name of downloaded)assert(fs.statSync(path.join(downloads,name)).size>0);mark('Real local image,WAV,Markdown,text download bytes',downloaded);
await click('[data-action=preview][data-id=result-3]');const playback=await evalJS(`(async()=>{const a=document.querySelector('dialog audio');await a.play();return {playing:!a.paused,duration:a.duration}})()`);assert(playback.playing);assert.equal(playback.duration,2);await click('[data-action=close-dialog]');mark('Native WAV audio playback');
await viewport(390,844);await navigate('chat');await capture('mobile-chat-active');await geometry('mobile-chat-active');await click('[data-action=composer-more]');await click('[data-action=composer-materials]');await capture('mobile-materials');await geometry('mobile-materials');await click('[data-action=close-dialog]');await viewport(1440,1000);await navigate('chat');
await click('[data-action=save][data-id=result-2]');await navigate('workspace');assert(await evalJS('document.querySelector(".treasure-file-list").innerText.includes("小鸟-第2稿")'));await capture('desktop-workspace');await navigate('chat');
await navigate('detail');await click('.matter-results-action');assert(!await evalJS('document.querySelector(".mmd-final-adjust").open'));await evalJS('document.querySelector(".mmd-final-adjust").open=true');for(const id of await evalJS('finalDraft.slice()'))await change(`[data-final=${id}]`,false);await change('[data-final=result-2]',true);await change('[data-final=result-5]',true);await capture('desktop-accept');await geometry('desktop-accept');await nativeClick('[data-action=finish]');assert(await evalJS('state.task.complete'));assert.equal(await evalJS('state.final.length'),2);await capture('desktop-complete');mark('Optional workspace save; exact multi-type final selection; complete state');
for(const width of [390,320]){await viewport(width,844);for(const p of ['home','tasks','create','agents','detail','chat','workspace','mine']){await navigate(p);await geometry(width+'-'+p);if(width===390)await capture('mobile-'+p);}await navigate('chat');await navigate('detail');await click('.matter-results-action');await geometry(width+'-accept');if(width===390)await capture('mobile-accept');await click('[data-action=close-dialog]');}
await viewport(390,844);await navigate('home');for(const [key,target] of Object.entries({tasks:'tasks',treasure:'workspace',mine:'mine',overview:'home'})){await nativeClick(`.workbench-mobile-nav [data-workbench-tab=${key}]`);assert.equal(await evalJS('page'),target);}mark('Original mobile bottom navigation with native clicks');
await type('.overview-quick-request textarea','帮我');await evalJS('state.draftFiles=[]');await nativeClick('.overview-quick-request button.primary');await nativeClick('.agent-row');await nativeClick('[data-action=assign]');await delay(800);assert.equal(await evalJS('state.outputs.length'),0);assert(await evalJS('state.messages[1].text.includes("希望完成什么")'));await capture('mobile-clarify');mark('No-attachment submission and natural clarification');
await type('.composer-textarea','只需要一段文字介绍');await nativeClick('.composer-send');await delay(800);assert.equal(await evalJS('state.outputs[0].type'),'text');await navigate('detail');await click('.matter-results-action');const finalID=await evalJS('state.outputs[0].id');assert.deepEqual(await evalJS('finalDraft'),[finalID]);await nativeClick('[data-action=finish]');assert(await evalJS('state.task.complete'));assert(!await evalJS(`state.saved.includes('${finalID}')`));mark('Default latest reply delivery; text-only acceptance without workspace save');
await navigate('chat');await evalJS(`document.querySelector('.text-selection-archive').open=true`);await type('[data-message-text="0"]','保留的需求文字');await click('[data-action=save-text]');assert(await evalJS('state.archive.some(a=>a.text==="保留的需求文字")'));await navigate('workspace');assert(await evalJS('document.querySelector(".treasure-file-list").innerText.includes("议事文字片段")'));mark('Editable text fragment save; previous saved assets survive new task');
await navigate('tasks');assert.equal(await evalJS('document.querySelectorAll(".task-create-actions button").length'),1);assert.equal(await evalJS('document.querySelector(".task-create-actions button").innerText'),'提出需求');await click('.task-create-actions button');assert.equal(await evalJS('page'),'create');mark('One create entry replaces three technical categories');assert.equal(errors.length,0,errors.join('\n'));fs.writeFileSync(root+'/prototype-checks.json',JSON.stringify({kind:'incremental-current-ui-adjusted-prototype',sourceHashes:Object.fromEntries(['index.html','adjusted.js','adjusted.css','../current/snapshots.js'].map(f=>[f,require('crypto').createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex')])),browser:await call('Browser.getVersion'),checks,layouts,errors,externalNetwork:'https blocked; CSP default-src self and connect-src none',notProductionAcceptance:true},null,2)+'\n');console.log(JSON.stringify({checks:checks.length,layouts:layouts.length,errors:errors.length}));
})().catch(e=>{console.error(e.stack);process.exitCode=1;}).finally(async()=>{if(ws?.readyState===WebSocket.OPEN){try{await call('Browser.close');}catch{}ws.close();}if(child.exitCode===null)child.kill('SIGTERM');await delay(400);if(child.exitCode!==null)fs.rmSync(profile,{recursive:true,force:true});});
