'use strict';
// Read-only product baseline. Never import the production application runtime.
const snapshots=window.BASELINE_SNAPSHOTS;
const labels={home:'办事',tasks:'事项',create:'提出需求',agents:'点将册',detail:'事项详情',chat:'议事',workspace:'资料',mine:'我的',materials:'选择资料',reference:'选择参考图'};
let page='home',view='',toastTimer,requirement='';
function feedback(message){document.getElementById('prototype-feedback')?.remove();const box=document.createElement('div');box.id='prototype-feedback';box.role='status';box.textContent=message;document.body.append(box);clearTimeout(toastTimer);toastTimer=setTimeout(()=>box.remove(),2400);}
function syncViewport(){document.querySelectorAll('.juyi-page').forEach(e=>e.style.setProperty('--hall-visual-height',innerHeight+'px'));}
function render(){view=innerWidth<=900?'mobile':'desktop';const item=snapshots[view+'-'+page]||snapshots['desktop-home'];document.body.innerHTML=item.html;document.body.className=item.bodyClass;document.documentElement.className=item.htmlClass;document.title=labels[page]+' · 当前页面基线原型（示例数据）';syncViewport();const input=document.querySelector('.overview-quick-request textarea');if(input){input.value=requirement;const submit=document.querySelector('.overview-quick-request button.primary');if(submit)submit.disabled=!requirement.trim();}document.querySelectorAll('form').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();feedback('当前是现状原型，不创建真实事项或执行任务。')}));}
function go(next){if(!labels[next])return;page=next;history.replaceState(null,'','#'+page);render();}
window.addEventListener('hashchange',()=>{const next=location.hash.slice(1);if(labels[next]){page=next;render()}});
window.addEventListener('resize',()=>{if(view!==(innerWidth<=900?'mobile':'desktop'))render();else syncViewport()});
document.addEventListener('input',e=>{if(e.target.matches('.overview-quick-request textarea')){requirement=e.target.value;const submit=document.querySelector('.overview-quick-request button.primary');if(submit)submit.disabled=!requirement.trim();}});
document.addEventListener('click',e=>{const target=e.target.closest('button,a,[data-prototype-page]');if(!target||target.disabled)return;e.preventDefault();if(target.dataset.prototypePage){go(target.dataset.prototypePage);return;}if(target.closest('.quick-material-files,.quick-reference-files')){target.classList.toggle('selected');target.setAttribute('aria-pressed',target.classList.contains('selected'));const count=document.querySelectorAll('.quick-material-files .selected,.quick-reference-files .selected').length;const confirm=document.querySelector('.quick-material-confirm,.quick-reference-confirm');if(confirm){confirm.textContent='确认选择（'+count+'）';confirm.disabled=false;}return;}const text=target.textContent.trim();if(text.startsWith('确认选择')){go('home');feedback('已查看选择交互；本次只还原现状，不写入资料关联。');return;}if(target.matches('.workbench-mobile-more')){document.querySelector('.workbench-more-menu')?.remove();feedback('底部可切换办事、事项、资料、我的；其他入口保持现有产品。');return;}feedback('这是现状基线原型；该操作不调用真实服务。');});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&page!=='home')go(page==='chat'?'detail':'home')});
const initial=location.hash.slice(1);page=labels[initial]?initial:'home';render();
