// Owned Chromium, offline UI prototype only. No product build, API or Provider.
const fs=require('fs'),path=require('path'),cp=require('child_process'),assert=require('assert'),crypto=require('crypto'),WebSocket=require('/home/isp/wsps/cyf/web/node_modules/ws');
const root=path.resolve(__dirname,'../prototype'),origin=process.env.PROTOTYPE_ORIGIN||'http://127.0.0.1:18766';
const profile=fs.mkdtempSync('/var/tmp/cyf-ui-baseline-browser-'),downloads=path.join(profile,'downloads');fs.mkdirSync(downloads);
const child=cp.spawn('/usr/bin/chromium-browser',['--headless','--no-sandbox','--disable-gpu','--no-first-run','--disable-background-networking','--disable-component-update','--disable-sync','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{stdio:['ignore','ignore','ignore']});
const delay=ms=>new Promise(r=>setTimeout(r,ms));let ws,id=0,loaded=0;const pending=new Map(),checks=[],layouts=[],errors=[],external=[];
function call(method,params={}){return new Promise((r,j)=>{const n=++id;const timer=setTimeout(()=>{pending.delete(n);j(Error('Owned browser diagnostic command stalled: '+method));},45000);pending.set(n,{r:v=>{clearTimeout(timer);r(v)},j:e=>{clearTimeout(timer);j(e)}});ws.send(JSON.stringify({id:n,method,params}));});}
async function ev(expression){const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true,userGesture:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;}
async function click(selector){const pos=await ev(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e||e.disabled)throw Error('missing/enabled '+${JSON.stringify(selector)});e.scrollIntoView({block:'center'});const r=e.getBoundingClientRect();if(!r.width||!r.height)throw Error('not visible '+${JSON.stringify(selector)});const hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);if(!e.contains(hit))throw Error('obscured '+${JSON.stringify(selector)});return{x:r.x+r.width/2,y:r.y+r.height/2}})()`);await call('Input.dispatchMouseEvent',{type:'mousePressed',...pos,button:'left',clickCount:1});await call('Input.dispatchMouseEvent',{type:'mouseReleased',...pos,button:'left',clickCount:1});await delay(90);}
async function type(selector,text){await ev(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e)throw Error('input missing');e.value=${JSON.stringify(text)};e.dispatchEvent(new Event('input',{bubbles:true}))})()`);}
async function viewport(w){await call('Emulation.setDeviceMetricsOverride',{width:w,height:w===1440?1000:844,deviceScaleFactor:1,mobile:w<721});}
async function go(p){await ev(`go(${JSON.stringify(p)})`);await delay(100);}
function mark(name){checks.push({name,pass:true});console.log('PASS '+name);}
async function snap(name){const r=await call('Page.captureScreenshot',{format:'png',fromSurface:true});fs.writeFileSync(root+'/screenshots/'+name+'.png',Buffer.from(r.data,'base64'));}
async function geometry(name){const g=await ev(`({width:innerWidth,scroll:document.documentElement.scrollWidth,dialog:document.querySelector('dialog[open]')?.getBoundingClientRect().toJSON(),badImages:[...document.images].filter(e=>e.getBoundingClientRect().width&&!e.naturalWidth).map(e=>e.src)})`);assert(g.scroll<=g.width+1,name+JSON.stringify(g));assert(!g.badImages.length,name+JSON.stringify(g));if(g.dialog)assert(g.dialog.x>=-1&&g.dialog.right<=g.width+1,name+JSON.stringify(g));layouts.push({name,...g});}
async function load(scenario='ready',expectedPage='home',reset=true){const fixture=String(Date.now());await call('Page.navigate',{url:origin+'/index.html?scenario='+scenario+(reset?'&reset=1':'')+'&fixture='+fixture+'#'+expectedPage});for(let i=0;i<300;i++){await delay(100);if(await ev(`typeof page!=="undefined"&&page===${JSON.stringify(expectedPage)}&&document.readyState==="complete"&&new URL(location.href).searchParams.get('fixture')===${JSON.stringify(fixture)}`))return;}throw Error('requested prototype document did not initialize: '+expectedPage);}
async function reload(){const before=loaded;await call('Page.reload',{ignoreCache:true});for(let i=0;i<300&&loaded===before;i++)await delay(100);assert(loaded>before,'reload document load event');for(let i=0;i<100;i++){if(await ev('typeof state!=="undefined"&&document.readyState==="complete"'))return;await delay(100);}throw Error('reload script initialization missing');}
async function createText(){await type('.overview-quick-request textarea','只需要一段文字介绍');await click('.overview-quick-request button.primary');assert.equal(await ev('state.draft'),'');assert.equal(await ev('state.draftFiles.length'),0);await click('.agent-row');await click('[data-action=assign]');await delay(750);assert.equal(await ev('page'),'chat');}
(async()=>{let port;for(let i=0;i<150;i++){const p=path.join(profile,'DevToolsActivePort');if(fs.existsSync(p)){port=fs.readFileSync(p,'utf8').split('\n')[0];break;}await delay(100);}assert(port,'owned Chromium startup');const targets=await fetch('http://127.0.0.1:'+port+'/json').then(r=>r.json());ws=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.once('open',r));ws.on('message',raw=>{const m=JSON.parse(raw);if(pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.j(Error(m.error.message)):p.r(m.result);}if(m.method==='Page.loadEventFired')loaded++;if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text);if(m.method==='Network.requestWillBeSent'&&!m.params.request.url.startsWith(origin)&&!m.params.request.url.startsWith('data:')&&!m.params.request.url.startsWith('blob:'))external.push(m.params.request.url);});await call('Page.enable');await call('Runtime.enable');await call('Network.enable');await call('Network.setBlockedURLs',{urls:['https://*']});
for(const w of [1440,390]){await viewport(w);const before=loaded;await call('Page.navigate',{url:origin+'/pages.html'});while(loaded===before)await delay(100);await geometry('page-index-'+w);await snap('page-index-'+w);assert.equal(await ev('document.querySelectorAll("article").length'),33);const links=await ev('[...document.querySelectorAll("a")].map(a=>a.href)');for(const u of links){const response=await fetch(u.split('#')[0]);assert(response.ok,u+' '+response.status);}mark('page index 18 pages / 15 states and HTTP-resolvable links at '+w);await click('a[href*="scenario=results"]');await delay(500);for(let i=0;i<100&&!await ev('typeof state!=="undefined"');i++)await delay(100);assert.equal(await ev('page'),'chat');assert.equal(await ev('state.outputs.length'),4);}
await load('ready','home');const capsule=await ev('(()=>{const s=getComputedStyle(document.querySelector(".overview-tabs button[aria-pressed=true]"));return {radius:s.borderRadius,background:s.backgroundColor,border:s.borderBottomWidth}})()');assert.equal(capsule.radius,'8px');assert.equal(capsule.background,'rgb(247, 234, 230)');assert.equal(capsule.border,'0px');mark('actual computed capsule selected CSS');fs.writeFileSync(root+'/preview-checks-20261007.json',JSON.stringify({status:'PASS',checks,layouts,capsule,errors,productAcceptance:false},null,2)+'\n');})().catch(e=>{console.error(e.stack);process.exitCode=1;}).finally(async()=>{if(ws?.readyState===WebSocket.OPEN){try{await call('Browser.close');}catch{}ws.close();}if(child.exitCode===null)child.kill('SIGTERM');await delay(400);if(child.exitCode!==null)fs.rmSync(profile,{recursive:true,force:true});});