// Lightweight offline-prototype browser check; no product build or Provider calls.
const fs=require('fs'),path=require('path'),os=require('os'),cp=require('child_process'),assert=require('assert'),WebSocket=require('/home/isp/wsps/cyf/web/node_modules/ws');
const root=__dirname;
const profile=fs.mkdtempSync('/var/tmp/cyf-prototype-chromium-');const downloads=path.join(profile,'downloads');fs.mkdirSync(downloads);
const child=cp.spawn('/usr/bin/chromium-browser',['--headless','--no-sandbox','--disable-gpu','--no-first-run','--no-default-browser-check','--disable-background-networking','--disable-component-update','--disable-sync','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{stdio:['ignore','ignore','pipe']});
const delay=ms=>new Promise(r=>setTimeout(r,ms));let ws,id=0;const pending=new Map(),errors=[],checks=[],layouts=[];const mark=(name,details)=>{checks.push({name,pass:true,details});console.log('PASS '+name);};
async function call(method,params={}){const n=++id;return new Promise((resolve,reject)=>{pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));});}
async function evalJS(expression){const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true,userGesture:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;}
async function click(selector){await evalJS(`(()=>{const x=document.querySelector(${JSON.stringify(selector)});if(!x)throw Error('missing '+${JSON.stringify(selector)});x.click();return true})()`);await delay(65);}
async function viewport(w,h){await call('Emulation.setDeviceMetricsOverride',{width:w,height:h,deviceScaleFactor:1,mobile:w<721});}
async function navigate(page){await evalJS(`go(${JSON.stringify(page)})`);await delay(100);}
async function capture(name){await delay(100);const shot=await call('Page.captureScreenshot',{format:'png',fromSurface:true});fs.writeFileSync(path.join(root,'screenshots',name+'.png'),Buffer.from(shot.data,'base64'));}
(async()=>{let port;for(let i=0;i<150;i++){if(fs.existsSync(path.join(profile,'DevToolsActivePort'))){port=fs.readFileSync(path.join(profile,'DevToolsActivePort'),'utf8').split('\n')[0];break;}await delay(100);}const targets=await fetch('http://127.0.0.1:'+port+'/json').then(r=>r.json());ws=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.once('open',r));ws.on('message',data=>{const x=JSON.parse(data);if(x.id&&pending.has(x.id)){const p=pending.get(x.id);pending.delete(x.id);x.error?p.reject(Error(JSON.stringify(x.error))):p.resolve(x.result);}if(x.method==='Runtime.exceptionThrown')errors.push(x.params.exceptionDetails.text);});await call('Runtime.enable');await call('Page.enable');await call('Network.enable');await call('Network.setBlockedURLs',{urls:['https://*']});await viewport(1440,1000);await call('Page.navigate',{url:(process.env.PROTOTYPE_ORIGIN||'http://127.0.0.1:35111')+'/complete-20261007/index.html'});await delay(700);

async function type(selector,value){await evalJS(`(()=>{const t=document.querySelector(${JSON.stringify(selector)});t.value=${JSON.stringify(value)};t.dispatchEvent(new Event('input',{bubbles:true}));})()`);}
async function change(selector,checked){await evalJS(`(()=>{const t=document.querySelector(${JSON.stringify(selector)});t.checked=${checked};t.dispatchEvent(new Event('change',{bubbles:true}));})()`);}
async function nativeClick(selector){const r=await evalJS(`(()=>{let e=document.querySelector(${JSON.stringify(selector)});e.scrollIntoView({block:'center'});let r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`);await call('Input.dispatchMouseEvent',{type:'mousePressed',...r,button:'left',clickCount:1});await call('Input.dispatchMouseEvent',{type:'mouseReleased',...r,button:'left',clickCount:1});await delay(100);}
async function geometry(label){let g=await evalJS(`({width:innerWidth,scroll:document.documentElement.scrollWidth,dialog:document.querySelector('dialog[open]')?.getBoundingClientRect().toJSON(),composer:document.querySelector('.composer-body')?.getBoundingClientRect().toJSON(),bottom:[...document.querySelectorAll('.workbench-mobile-nav button')].filter(e=>e.getBoundingClientRect().width).map(e=>e.textContent.trim()),badImages:[...document.images].filter(e=>e.getBoundingClientRect().width&&!e.naturalWidth).map(e=>e.src)})`);assert(g.scroll<=g.width+1,label+JSON.stringify(g));assert.equal(g.badImages.length,0,JSON.stringify(g));if(g.dialog)assert(g.dialog.x>=0&&g.dialog.right<=g.width+1);layouts.push({label,...g});}
assert.equal(await evalJS('document.querySelectorAll(".quick-reference-open,.composer-execute").length'),0);
await type('.overview-quick-request textarea','画一只鸟');await nativeClick('.quick-material-open');await capture('desktop-materials');await geometry('desktop-materials');
for(const id of ['ref-bird','ref-brief','ref-audio'])await change(`[data-pick="${id}"]`,true);
await click('[data-action=confirm-materials]');assert.equal(await evalJS('state.draftFiles.length'),3);await capture('desktop-home');
await click('[data-action=remove][data-id=ref-audio]');assert.equal(await evalJS('state.draftFiles.length'),2);
await click('.quick-material-open');await change('[data-pick=ref-audio]',true);await click('[data-action=close-dialog]');assert.equal(await evalJS('state.draftFiles.length'),2);mark('Unified multi-type materials; remove and cancel semantics');
await nativeClick('.overview-quick-request button.primary');assert.equal(await evalJS('page'),'agents');await nativeClick('.agent-row');assert(!await evalJS('document.querySelector(".agent-panel").innerText.includes("画一只鸟")'));assert.equal(await evalJS('document.querySelectorAll(".agent-panel .mmd-attachments").length'),0);mark('Roster contains Agent information, not requirement or materials');await capture('desktop-agents');await geometry('desktop-agents');await nativeClick('[data-action=assign]');await delay(800);
assert.equal(await evalJS('state.messages[0].files.length'),2);assert.equal(await evalJS('state.messages[0].text'),'画一只鸟');assert.equal(await evalJS('state.outputs[0].type'),'image');mark('Explicit chosen Agent; automatic requirement and files; direct reply');assert.equal(await evalJS('document.querySelectorAll(".chat-panel .toolbar-actions,.chat-panel .hall-voice-controls,.chat-panel .composer-context").length'),0);assert.equal(await evalJS('document.querySelectorAll(".composer-actions button").length'),2);mark('Chat removes navigation shortcuts; only plus and send in integrated composer');await capture('desktop-chat');await geometry('desktop-chat');
await click('[data-action=preview][data-id=result-1]');await capture('desktop-preview');await click('[data-action=close-dialog]');await click('[data-action=quote][data-id=result-1]');await type('.composer-textarea','把这一稿改成黄色，再附上音频和活动方案，以及文字介绍');await nativeClick('.composer-send');await delay(800);
assert.equal(await evalJS('state.messages[2].quote'),'result-1');assert.equal(await evalJS('state.outputs.length'),5);assert.deepEqual(await evalJS('state.outputs.map(x=>x.type)'),['image','image','audio','document','text']);mark('Quoted revision retained; text,image,audio,document outputs');
await nativeClick('[data-action=composer-more]');await click('[data-action=composer-materials]');await change('[data-pick=ref-audio]',true);await click('[data-action=confirm-materials]');await nativeClick('.composer-send');await delay(800);assert.equal(await evalJS('state.messages[4].files[0]'),'ref-audio');mark('Attachment-only follow-up');
await call('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:downloads});
for(const id of ['result-1','result-3','result-4','result-5'])await evalJS(`download('${id}')`);await delay(700);const downloaded=fs.readdirSync(downloads);assert(downloaded.length>=4,downloaded.join(','));for(const name of downloaded)assert(fs.statSync(path.join(downloads,name)).size>0);mark('Real local image,WAV,Markdown,text download bytes',downloaded);
await click('[data-action=preview][data-id=result-3]');const playback=await evalJS(`(async()=>{const a=document.querySelector('dialog audio');await a.play();return {playing:!a.paused,duration:a.duration}})()`);assert(playback.playing);assert.equal(playback.duration,2);await click('[data-action=close-dialog]');mark('Native WAV audio playback');
await viewport(390,844);await navigate('chat');await capture('mobile-chat-active');await geometry('mobile-chat-active');await click('[data-action=composer-more]');await click('[data-action=composer-materials]');await capture('mobile-materials');await geometry('mobile-materials');await click('[data-action=close-dialog]');await viewport(1440,1000);await navigate('chat');
await click('[data-action=save][data-id=result-2]');await navigate('workspace');assert(await evalJS('document.querySelector(".treasure-file-list").innerText.includes("小鸟-第2稿")'));await capture('desktop-workspace');await navigate('chat');
await navigate('detail');await click('.matter-results-action');assert.equal(await evalJS('document.querySelectorAll("dialog input[type=checkbox],.mmd-final-adjust").length'),0);assert.deepEqual(await evalJS('finalDraft'),['result-3','result-4','result-5','result-6']);await click('[data-action=continue-chat]');assert.equal(await evalJS('page'),'chat');await click('.panel-return');assert.equal(await evalJS('page'),'detail');await click('.matter-results-action');await capture('desktop-accept');await geometry('desktop-accept');await nativeClick('[data-action=finish]');await delay(750);assert(await evalJS('state.task.complete'));assert.equal(await evalJS('state.final.length'),4);await capture('desktop-complete');mark('No acceptance checkboxes; modify in original conversation; freeze current delivery including unchanged media');
for(const width of [390,320]){await viewport(width,844);for(const p of ['home','tasks','create','agents','detail','chat','workspace','mine']){await navigate(p);await geometry(width+'-'+p);if(width===390)await capture('mobile-'+p);}await navigate('chat');await navigate('detail');await click('.matter-results-action');await geometry(width+'-accept');if(width===390)await capture('mobile-accept');await click('[data-action=close-dialog]');}
await viewport(390,844);await navigate('home');for(const [key,target] of Object.entries({tasks:'tasks',treasure:'workspace',mine:'mine',overview:'home'})){await nativeClick(`.workbench-mobile-nav [data-workbench-tab=${key}]`);assert.equal(await evalJS('page'),target);}mark('Original mobile bottom navigation with native clicks');
await type('.overview-quick-request textarea','帮我');await evalJS('state.draftFiles=[]');await nativeClick('.overview-quick-request button.primary');await nativeClick('.agent-row');await nativeClick('[data-action=assign]');await delay(800);assert.equal(await evalJS('state.outputs.length'),0);assert(await evalJS('state.messages[1].text.includes("希望完成什么")'));await capture('mobile-clarify');mark('No-attachment submission and natural clarification');
await type('.composer-textarea','只需要一段文字介绍');await nativeClick('.composer-send');await delay(800);assert.equal(await evalJS('state.outputs[0].type'),'text');await navigate('detail');await click('.matter-results-action');const finalID=await evalJS('state.outputs[0].id');assert.deepEqual(await evalJS('finalDraft'),[finalID]);await nativeClick('[data-action=finish]');await delay(750);assert(await evalJS('state.task.complete'));assert(!await evalJS(`state.saved.includes('${finalID}')`));mark('Default latest reply delivery; text-only acceptance without workspace save');
await navigate('chat');await evalJS(`document.querySelector('.text-selection-archive').open=true`);await type('[data-message-text="0"]','保留的需求文字');await click('[data-action=save-text]');assert(await evalJS('state.archive.some(a=>a.text==="保留的需求文字")'));await navigate('workspace');assert(await evalJS('document.querySelector(".treasure-file-list").innerText.includes("议事文字片段")'));mark('Editable text fragment save; previous saved assets survive new task');
await navigate('tasks');assert.equal(await evalJS('document.querySelectorAll(".task-create-actions button").length'),1);assert.equal(await evalJS('document.querySelector(".task-create-actions button").innerText'),'提出需求');await click('.task-create-actions button');assert.equal(await evalJS('page'),'create');mark('One create entry replaces three technical categories');
const formalBefore=await evalJS('JSON.stringify({task:state.task,agent:state.agent,messages:state.messages,outputs:state.outputs,final:state.final,delivery:state.delivery})');
await navigate('agents');await click('.agent-row[data-agent="0"]');assert(await evalJS('!!document.querySelector("[data-action=private-chat]")'));assert(!await evalJS('!!document.querySelector("[data-action=assign]")'));await click('[data-action=private-chat]');assert.equal(await evalJS('page'),'private');assert.equal(await evalJS('conversation().messages.length'),0);await type('.composer-textarea','你好');await nativeClick('.composer-send');await delay(800);assert.equal(await evalJS('conversation().messages.length'),2);assert.equal(await evalJS('conversation().outputs.length'),0);
await click('[data-action=composer-more]');await click('[data-action=composer-materials]');await change('[data-pick=ref-brief]',true);await click('[data-action=confirm-materials]');await type('.composer-textarea','请整理成文档');await nativeClick('.composer-send');await delay(800);const privateResult=await evalJS('conversation().outputs[0].id');await click(`[data-action=save][data-id=${privateResult}]`);assert(await evalJS(`state.saved.includes('${privateResult}')`));
await capture('mobile-private');await geometry('mobile-private');await viewport(1440,1000);await capture('desktop-private');await geometry('desktop-private');
await click('.panel-return');assert.equal(await evalJS('page'),'agents');await click('.agent-row[data-agent="4"]');await click('[data-action=private-chat]');assert.equal(await evalJS('conversation().agent.name'),'吴用');assert.equal(await evalJS('conversation().messages.length'),0);await click('.panel-return');await click('.agent-row[data-agent="0"]');await click('[data-action=private-chat]');assert.equal(await evalJS('conversation().messages.length'),4);
assert.equal(await evalJS('JSON.stringify({task:state.task,agent:state.agent,messages:state.messages,outputs:state.outputs,final:state.final,delivery:state.delivery})'),formalBefore);mark('Restored real private-chat prototype branch; per-Agent history and materials isolated from formal task');
await click('[data-action=composer-more]');await click('[data-action=voice-record]');await click('[data-action=close-dialog]');assert.equal(await evalJS('conversation().chatDraft'),'');await click('[data-action=composer-more]');await click('[data-action=voice-record]');await click('[data-action=voice-stop]');await type('.mmd-voice-transcript textarea','这是待确认的语音文字');await click('[data-action=voice-use]');assert.equal(await evalJS('conversation().chatDraft'),'这是待确认的语音文字');assert.equal(await evalJS('conversation().messages.length'),4);await capture('desktop-private-draft');
await click('[data-action=composer-more]');await click('[data-action=voice-settings]');await evalJS('document.querySelector(".mmd-voice-language").value="en-US"');await click('[data-action=voice-settings-save]');assert.equal(await evalJS('state.voiceLanguage'),'en-US');mark('Voice mock: cancel, stop, edit transcript, insert draft without auto-send, settings');
await call('Page.reload',{ignoreCache:true});await delay(800);assert.equal(await evalJS('page'),'private');assert.equal(await evalJS('conversation().agent.name'),'公孙胜');assert.equal(await evalJS('conversation().messages.length'),4);assert.equal(await evalJS('conversation().chatDraft'),'这是待确认的语音文字');assert.equal(await evalJS('state.voiceLanguage'),'en-US');assert(await evalJS('state.task.complete'));mark('Reload preserves prototype draft, private history, formal completion and optional workspace saves');
await click('.panel-return');await evalJS('state.task=null;state.agent=null;renderAgents()');assert.equal(await evalJS('document.querySelectorAll("[data-action=assign]").length'),0);await click('[data-action=private-chat]');assert.equal(await evalJS('state.task'),null);mark('Browsing roster and private chatting never invents a requirement');

async function loadScenario(name){const nav=await call('Page.navigate',{url:(process.env.PROTOTYPE_ORIGIN||'http://127.0.0.1:35111')+'/complete-20261007/index.html?scenario='+name});if(nav.errorText)throw Error(nav.errorText);let ready=false;for(let i=0;i<100;i++){await delay(100);try{ready=await evalJS(`typeof scenario==='string'&&scenario===${JSON.stringify(name)}&&typeof go==='function'&&!!document.querySelector('.juyi-page')`);}catch{}if(ready)break;}assert(ready,'scenario document not ready: '+name);await navigate('home');assert(await evalJS('!!document.querySelector(".overview-quick-request textarea")'),'home input missing '+name+' '+await evalJS('location.href'));}
async function createTextTask(){await type('.overview-quick-request textarea','只需要文字介绍');await nativeClick('.overview-quick-request button.primary');assert.equal(await evalJS('state.draft'),'');assert.equal(await evalJS('state.draftFiles.length'),0);await nativeClick('.agent-row');await nativeClick('[data-action=assign]');await delay(800);}
await loadScenario('attachment-only');await click('.quick-material-open');await change('[data-pick=ref-brief]',true);await click('[data-action=confirm-materials]');assert.equal(await evalJS('document.querySelector(".overview-quick-request button.primary").disabled'),false);await nativeClick('.overview-quick-request button.primary');assert.equal(await evalJS('page'),'agents');assert.equal(await evalJS('state.draftFiles.length'),0);await nativeClick('.agent-row');await nativeClick('[data-action=assign]');await delay(800);assert.equal(await evalJS('state.messages[0].files.length'),1);assert.equal(await evalJS('state.outputs.length'),0);await capture('attachment-only-clarification');mark('Attachment-only create; no hidden generation; natural clarification before deliverable');
for(const name of ['create-failure','create-unknown']){await loadScenario(name);await type('.overview-quick-request textarea','保留草稿');await click('.quick-material-open');await change('[data-pick=ref-brief]',true);await click('[data-action=confirm-materials]');await nativeClick('.overview-quick-request button.primary');assert.equal(await evalJS('state.task'),null);assert.equal(await evalJS('state.draft'),'保留草稿');assert.equal(await evalJS('state.draftFiles.length'),1);await capture(name);await click('[data-action=create-status]');assert.equal(await evalJS('state.task'),null);mark(name+' preserves draft and attachments; status check does not create');}
await loadScenario('normal-extended');await createTextTask();assert.equal(await evalJS('state.messages.filter(m=>m.role==="USER").length'),1);assert.equal(await evalJS('document.querySelectorAll(".hall-message.USER .message-content p").length'),1);await click('.panel-return');assert.equal(await evalJS('page'),'detail');mark('SF01 direct return to exact task; SF03 clear successful submitted draft; SF05 single original demand');
await click('.matter-results-action');await nativeClick('[data-action=finish]');await delay(750);assert.equal(await evalJS('state.operation.writes'),1);await navigate('home');assert(await evalJS('document.querySelector(".overview-item").innerText.includes("已完成")'));await navigate('detail');await click('.matter-results-action');assert.equal(await evalJS('document.querySelectorAll("[data-action=finish],[data-action=continue-chat]").length'),0);await click('[data-action=close-dialog]');await navigate('chat');assert(await evalJS('document.querySelector(".composer-send").disabled'));assert.equal(await evalJS('document.querySelectorAll("[data-action=quote]").length'),0);await call('Page.reload',{ignoreCache:true});await delay(750);assert(await evalJS('state.task.complete'));assert.equal(await evalJS('state.operation.writes'),1);mark('SF02 completion projects without reload; SF04 refresh preserves same operation; completed task read-only');
await navigate('tasks');await click('[data-filter="待点将"]');assert(await evalJS('document.querySelector(".mmd-empty").innerText.includes("暂无")'));await click('[data-filter="已完成"]');assert(await evalJS('document.querySelector(".task-card").offsetParent!==null'));mark('Task filter empty/completed and exact demo detail navigation');
for(const name of ['accept-unknown','accept-failure']){await loadScenario(name);await createTextTask();await click('.panel-return');await click('.matter-results-action');await nativeClick('[data-action=finish]');const before=await evalJS('JSON.stringify(state.operation)');await delay(750);assert(!await evalJS('state.task.complete'));assert.equal(await evalJS('state.operation.writes'),1);assert.equal(await evalJS('document.querySelector(".matter-advice-heading strong").innerText'),name==='accept-unknown'?'验收待核对':'验收未完成');await capture(name);await call('Page.reload',{ignoreCache:true});await delay(750);await navigate('detail');await click('.matter-results-action');assert.equal(await evalJS('document.querySelectorAll("[data-action=finish]").length'),0);await click('[data-action=operation-status]');assert.equal(await evalJS('state.operation.writes'),1);assert(!await evalJS('state.task.complete'));mark(name+' status unknown/failed; refresh and queries never re-submit');}
await loadScenario('reply-failure');await createTextTask();const count=await evalJS('state.messages.length');await type('.composer-textarea','这一稿继续调整');await click('[data-action=composer-more]');await click('[data-action=composer-materials]');await change('[data-pick=ref-brief]',true);await click('[data-action=confirm-materials]');await nativeClick('.composer-send');assert.equal(await evalJS('state.messages.length'),count);assert.equal(await evalJS('state.chatDraft'),'这一稿继续调整');assert.equal(await evalJS('state.chatFiles.length'),1);await capture('reply-failure');await click('[data-action=reply-status]');assert.equal(await evalJS('state.messages.length'),count);await nativeClick('.composer-send');await delay(750);assert.equal(await evalJS('state.messages.length'),count+2);mark('Failed/ambiguous send preserves attachments and text; only explicit resend after checking');
await loadScenario('independent-roots');await createTextTask();await click('.panel-return');await click('.matter-results-action');assert(await evalJS('document.querySelector("dialog").innerText.includes("待实现（R01）")'));assert.equal(await evalJS('document.querySelectorAll("[data-action=finish]").length'),0);await capture('independent-roots');mark('R01 independent roots explicitly blocked; no fake source recovery implementation');
await loadScenario('normal-local-files');await click('.quick-material-open');const fixture=path.join(downloads,'local-example.txt');fs.writeFileSync(fixture,'本机附件示例');await call('DOM.enable');let doc=await call('DOM.getDocument');let input=await call('DOM.querySelector',{nodeId:doc.root.nodeId,selector:'[data-local-files]'});await call('DOM.setFileInputFiles',{nodeId:input.nodeId,files:[fixture]});await delay(450);assert.equal(await evalJS('state.localFiles.length'),1);assert.equal(await evalJS('state.draftFiles.length'),0);await click('[data-action=close-dialog]');assert.equal(await evalJS('state.draftFiles.length'),0);await click('.quick-material-open');const localID=await evalJS('state.localFiles[0].id');await change('[data-pick="'+localID+'"]',true);await click('[data-action=confirm-materials]');assert.equal(await evalJS('state.draftFiles[0]'),localID);await click('[data-action=preview][data-id="'+localID+'"]');assert(await evalJS('document.querySelector("dialog").innerText.includes("本机附件示例")'));await capture('local-file-preview');mark('Native file picker; local text preview; cancel does not confirm attachments');


await loadScenario('pending-refresh');await createTextTask();await click('.panel-return');await click('.matter-results-action');await nativeClick('[data-action=finish]');const frozen=await evalJS('JSON.stringify({id:state.operation.id,outputs:state.operation.outputs})');await call('Page.reload',{ignoreCache:true});await delay(800);assert(await evalJS('state.task.complete'));assert.equal(await evalJS('state.operation.writes'),1);assert.equal(await evalJS('JSON.stringify({id:state.operation.id,outputs:state.operation.outputs})'),frozen);mark('Refresh during acceptance keeps frozen selection and original operation; local read-only recovery');
await loadScenario('leave-pending');await createTextTask();await click('.panel-return');await click('.matter-results-action');await nativeClick('[data-action=finish]');await click('[data-action=operation-detail]');await delay(750);assert(await evalJS('state.task.complete'));assert.equal(await evalJS('document.querySelector(".matter-advice-heading strong").innerText'),'已完成');assert.equal(await evalJS('state.operation.writes'),1);mark('Leaving acceptance progress still updates detail completion without reload or extra writes');
await loadScenario('reply-pending-refresh');await type('.overview-quick-request textarea','只需要文字介绍');await nativeClick('.overview-quick-request button.primary');await nativeClick('.agent-row');await nativeClick('[data-action=assign]');await call('Page.reload',{ignoreCache:true});await delay(800);assert.equal(await evalJS('state.outputs.length'),0);assert(await evalJS('state.error.includes("待核对")'));assert.equal(await evalJS('state.messages.filter(m=>m.role==="USER").length'),1);mark('Refresh while reply pending does not restart Agent simulation or duplicate demand');
for(const width of [390,320]){await viewport(width,844);for(const name of ['create-unknown','reply-failure','accept-unknown','accept-failure','independent-roots']){await loadScenario(name);await evalJS(`state.simulation={create:'ok',reply:'ok',accept:'ok'}`);await createTextTask();if(name==='create-unknown'){await navigate('home');await evalJS(`state.simulation.create='unknown'`);await type('.overview-quick-request textarea','待核对需求');await nativeClick('.overview-quick-request button.primary');}
else if(name==='reply-failure'){await evalJS(`state.simulation.reply='failed'`);await type('.composer-textarea','待核对回复');await nativeClick('.composer-send');}
else{await evalJS(`state.simulation.accept=${JSON.stringify(name==='accept-failure'?'failed':'unknown')}`);await click('.panel-return');await click('.matter-results-action');if(name==='independent-roots'){assert(await evalJS('document.querySelector("dialog").innerText.includes("待实现（R01）")'));}else{await nativeClick('[data-action=finish]');await delay(750);}}
await geometry(width+'-'+name);await capture(width+'-'+name);}}
await call('Page.navigate',{url:(process.env.PROTOTYPE_ORIGIN||'http://127.0.0.1:35111')+'/complete-20261007/scenarios.html'});await delay(500);assert.equal(await evalJS('document.querySelectorAll("article a").length'),8);await geometry('320-scenarios');mark('Eight linked scenario entries and all new recovery layouts at 390/320');

assert.equal(errors.length,0,errors.join('\n'));fs.writeFileSync(root+'/prototype-checks.json',JSON.stringify({kind:'browser-walkthrough-completed-interaction-prototype-20261007',sourceHashes:Object.fromEntries(['index.html','adjusted.js','adjusted.css','../current/snapshots.js','scenarios.html','scenarios.css','check.cjs'].map(f=>[f,require('crypto').createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex')])),browser:await call('Browser.getVersion'),checks,layouts,errors,externalNetwork:'https blocked; CSP default-src self and connect-src none',notProductionAcceptance:true},null,2)+'\n');console.log(JSON.stringify({checks:checks.length,layouts:layouts.length,errors:errors.length}));
})().catch(async e=>{console.error(e.stack);try{fs.writeFileSync(root+'/failure-diagnostic.json',JSON.stringify({error:e.message,checks,dom:await evalJS('({url:location.href,page:typeof page==="string"?page:null,text:document.body.innerText.slice(-4000)})')},null,2));}catch{}process.exitCode=1;}).finally(async()=>{if(ws?.readyState===WebSocket.OPEN){try{await call('Browser.close');}catch{}ws.close();}if(child.exitCode===null)child.kill('SIGTERM');await delay(400);if(child.exitCode!==null)fs.rmSync(profile,{recursive:true,force:true});});
