'use strict';
// Documentation-only, offline prototype. No API, authentication or Provider calls.
// Same demonstration bytes as bird.svg; embedded for reliable offline downloads.
const birdSvg = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 720 460\" role=\"img\" aria-label=\"原型示意：一只蓝色小鸟停在树枝上，非Agent生成结果\">\n<defs><linearGradient id=\"bg\" x2=\"1\" y2=\"1\"><stop stop-color=\"#e6eedc\"/><stop offset=\"1\" stop-color=\"#f5f0dc\"/></linearGradient><linearGradient id=\"body\" x2=\".8\" y2=\"1\"><stop stop-color=\"#6d9da4\"/><stop offset=\"1\" stop-color=\"#416d83\"/></linearGradient><filter id=\"blur\"><feGaussianBlur stdDeviation=\"15\"/></filter></defs>\n<rect width=\"720\" height=\"460\" fill=\"url(#bg)\"/>\n<g filter=\"url(#blur)\" opacity=\".44\"><circle cx=\"80\" cy=\"64\" r=\"85\" fill=\"#b3c6a4\"/><circle cx=\"656\" cy=\"133\" r=\"61\" fill=\"#c7d6b2\"/><circle cx=\"580\" cy=\"340\" r=\"78\" fill=\"#dbe4c9\"/></g>\n<g opacity=\".5\" fill=\"#abbc8b\"><ellipse cx=\"114\" cy=\"326\" rx=\"48\" ry=\"17\" transform=\"rotate(-31 114 326)\"/><ellipse cx=\"567\" cy=\"291\" rx=\"42\" ry=\"14\" transform=\"rotate(-28 567 291)\"/></g>\n<path d=\"M81 387 C244 337 445 380 658 280\" fill=\"none\" stroke=\"#927354\" stroke-width=\"14\" stroke-linecap=\"round\"/><path d=\"M158 370 L132 332 M505 333 L558 294\" fill=\"none\" stroke=\"#927354\" stroke-width=\"6\" stroke-linecap=\"round\"/>\n<path d=\"M337 292 L269 367 L323 347 L366 297\" fill=\"#446982\"/>\n<ellipse cx=\"378\" cy=\"258\" rx=\"69\" ry=\"81\" transform=\"rotate(21 378 258)\" fill=\"url(#body)\"/>\n<path d=\"M416 223 C442 259 432 308 393 328 C344 344 326 305 333 274 C346 300 390 289 416 223Z\" fill=\"#e8ddba\"/>\n<path d=\"M328 237 C283 281 323 323 380 292 C364 265 349 247 328 237Z\" fill=\"#53798f\"/>\n<path d=\"M324 249 C321 275 343 288 362 291 M316 266 C324 284 340 294 350 295\" fill=\"none\" stroke=\"#85a9af\" stroke-width=\"3\" stroke-linecap=\"round\"/>\n<circle cx=\"419\" cy=\"193\" r=\"48\" fill=\"#6d9da4\"/><path d=\"M402 229 Q438 247 456 208 L439 201Z\" fill=\"#f2e8c7\"/>\n<path d=\"M459 190 L493 200 L459 207Z\" fill=\"#5b665a\"/><circle cx=\"436\" cy=\"181\" r=\"6.5\" fill=\"#253d39\"/><circle cx=\"438\" cy=\"179\" r=\"2\" fill=\"#fff\"/>\n<path d=\"M379 331 L378 351 L366 355 M398 326 L401 350 L414 350\" fill=\"none\" stroke=\"#6c6652\" stroke-width=\"3.5\" stroke-linecap=\"round\"/>\n<g opacity=\".6\" fill=\"#b2c595\"><ellipse cx=\"574\" cy=\"285\" rx=\"28\" ry=\"12\" transform=\"rotate(-36 574 285)\"/><ellipse cx=\"605\" cy=\"295\" rx=\"21\" ry=\"9\" transform=\"rotate(13 605 295)\"/></g>\n</svg>\n";
const main = document.getElementById('main');
const dialog = document.getElementById('dialog');
const dialogBody = document.getElementById('dialog-body');
const toastBox = document.getElementById('toast');
const escapeText = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const files = [
  {id:'photo', name:'小鸟示意图.svg', type:'图片', tag:'图', size:'原型示意', kind:'image'},
  {id:'guide', name:'风格说明.txt', type:'文档', tag:'文', size:'1 KB', kind:'doc'},
  {id:'audio', name:'声音示意.wav', type:'音频', tag:'音', size:'2 秒 · 合成示意音', kind:'audio'},
  {id:'table', name:'素材清单.csv', type:'文件', tag:'表', size:'1 KB', kind:'doc'}
];
const agents = [
  {id:'yanqing', name:'燕青', face:'燕', description:'图像创作与内容表达'},
  {id:'wuyong', name:'吴用', face:'吴', description:'资料整理与方案分析'},
  {id:'songjiang', name:'宋江', face:'宋', description:'综合协作与任务推进'}
];
const state = {
  page:'request', requirement:'画一只鸟，配一段简短介绍。', materials:[], agent:'yanqing',
  message:'', messageMaterials:[], messages:[], quote:false, revision:1, saved:new Set(),
  accepted:new Set(['result','answer']), completed:[], pending:false, pickerTarget:'request', pickerDraft:new Set(),
  error:'', lastFocus:null, previewFromPicker:false, previewId:'result'
};
const labels = {request:'提需求',agents:'选 Agent',chat:'悬赏议事',accept:'验收成果',done:'已完成',space:'工作空间'};
let toastTimer;
function toast(text) { clearTimeout(toastTimer); toastBox.textContent=text;toastBox.classList.add('visible');toastTimer=setTimeout(()=>toastBox.classList.remove('visible'),2300); }
function primary(label,action,extra='') { return `<button type="button" class="primary-button" data-action="${action}" ${extra}>${label}</button>`; }
function steps(n) { const names=['提需求','选 Agent','会话调整','验收完成']; return `<div class="steps" aria-label="需求流程">${names.map((name,i)=>`${i?'<div class="step-line" aria-hidden="true"></div>':''}<div class="step ${i===n?'active':i<n?'complete':''}" ${i===n?'aria-current="step"':''}><span>${i<n?'✓':i+1}</span>${name}</div>`).join('')}</div>`; }
function byId(id) {
  if(id==='result')return {id,name:`小鸟示意图${state.revision>1?' · 第'+state.revision+'版':''}.svg`,type:'图片',tag:'图',kind:'image',size:'原型示意'};
  if(id==='answer')return {id,name:'小鸟介绍.txt',type:'文字',tag:'文',kind:'doc',size:'来自当前答复'};
  return files.find(file=>file.id===id) || files[0];
}
function fileDot(file) { return `<span class="file-dot ${file.kind}" aria-hidden="true">${file.tag}</span>`; }
function chips(ids,remove=false) { return ids.length?`<div class="materials">${ids.map(id=>{const file=byId(id);return `<div class="material-chip">${fileDot(file)}<button type="button" class="file-name" data-action="preview" data-file="${id}">${escapeText(file.name)}</button>${remove?`<button type="button" aria-label="移除 ${escapeText(file.name)}" data-action="remove-material" data-file="${id}">×</button>`:''}</div>`;}).join('')}</div>`:''; }
function agent() {return agents.find(a=>a.id===state.agent);}
function saveButton(id,style='') { return `<button type="button" class="${style} ${state.saved.has(id)?'saved':''}" data-action="save" data-file="${id}">${state.saved.has(id)?'已保存':'保存到工作空间'}</button>`; }
function audioMarkup() {return `<audio controls preload="metadata" src="${audioURL}" aria-label="播放原型合成示意音频"></audio>`;}
function resultCard() {return `<div class="result-card"><button type="button" style="display:block;width:100%;padding:0" data-action="preview" data-file="result" aria-label="预览小鸟示意图"><img class="result-image" src="bird.svg" alt="原型示意：一只蓝色小鸟停在树枝上"></button><div class="result-caption"><span>小鸟示意图.svg</span><small>原型示意 · 非生成结果</small></div><div class="result-actions"><button type="button" data-action="preview" data-file="result">预览</button><button type="button" data-action="download" data-file="result">下载</button>${saveButton('result')}</div></div>`;}
function resultBundle() {return `<div class="result-grid">${resultCard()}<div class="result-side"><div class="result-card file-card"><div class="file-row">${fileDot(byId('answer'))}<div><strong>小鸟介绍.txt</strong><small>文字也可以成为成果</small></div></div><div class="result-actions"><button data-action="preview" data-file="answer">预览</button><button data-action="download" data-file="answer">下载</button>${saveButton('answer')}</div></div><div class="result-card audio-card"><div class="file-row">${fileDot(byId('audio'))}<div><strong>声音示意.wav</strong><small>音频展示示例 · 非 Agent 生成</small></div></div>${audioMarkup()}<div class="result-actions"><button data-action="download" data-file="audio">下载</button>${saveButton('audio')}</div></div></div></div>`;}
function requestPage() {return `<section class="page narrow">${steps(0)}<div class="eyebrow">从一个想法开始</div><h1>说说你想做什么</h1><p class="intro">描述需求，交给合适的 Agent 一起完成。</p><div class="request-box"><label class="field-label" for="requirement">你的需求</label><textarea id="requirement" placeholder="例如：画一只鸟，配一段简短介绍。">${escapeText(state.requirement)}</textarea>${chips(state.materials,true)}<div class="request-tools"><button class="outline-button" data-action="materials">＋ 添加资料（可选）</button><span class="hint">图片、文档、音频等</span></div></div>${state.error?`<p class="error" role="alert">${escapeText(state.error)}</p>`:''}<div class="request-footer"><span class="hint">不添加资料，也可以直接开始。</span>${primary('选择 Agent →','choose-agent')}</div><div class="empty-tip"><strong>一个会话，完成协作。</strong><span>看结果、继续修改，满意后再验收。</span></div></section>`;}
function agentsPage() {return `<section class="page narrow">${steps(1)}<h1>选一位 Agent 来帮你</h1><p class="intro">选好后，需求和资料会自动发送到议事会话。</p><div class="summary-box"><div class="caption">本次需求</div><p>${escapeText(state.requirement||'画一只鸟，配一段简短介绍。')}</p><div class="hint">${state.materials.length?`已选 ${state.materials.length} 份资料`:'未添加资料'}</div></div><div class="agent-grid">${agents.map(a=>`<button class="agent-card" data-action="select-agent" data-agent="${a.id}" aria-pressed="${state.agent===a.id}"><span class="agent-avatar">${a.face}</span><h3>${a.name}</h3><p>${a.description}</p><span class="online">可以接收需求</span></button>`).join('')}</div><p class="agent-note">资料只发送给参与本次任务的 Agent。</p><div class="agent-footer"><button class="outline-button" data-page="request">返回修改</button>${primary('开始议事 →','start')}</div></section>`;}
function chatPage() {const a=agent();return `<section class="chat-page"><div class="chat-heading"><div><h1>小鸟创作<span class="status-pill">${state.pending?'处理中':'待验收'}</span></h1><p>悬赏议事 · ${a.name}</p></div><button class="outline-button" data-page="accept" ${state.pending?'disabled':''}>验收</button></div><div class="thread" id="thread"><div class="thread-inner"><p class="timeline-note">需求和资料已发送给 ${a.name}</p><div class="user-row"><div class="user-bubble">${escapeText(state.requirement||'画一只鸟，配一段简短介绍。')}${chips(state.materials)}</div></div><div class="assistant-row"><div class="agent-avatar">${a.face}</div><div class="assistant-body"><div class="speaker">${a.name}</div><p class="assistant-text">小鸟停在枝头，背景保持简洁。你可以先看看，也可以继续告诉我想调整哪里。</p>${resultBundle()}<button class="continue-button" data-action="quote">引用这张图，继续修改 ↗</button></div></div>${state.messages.map(m=>`<div class="${m.role==='user'?'user-row new-message':'assistant-row new-message'}">${m.role==='user'?`<div class="user-bubble">${escapeText(m.text)}${chips(m.materials||[])}</div>`:`<div class="agent-avatar">${a.face}</div><div class="assistant-body"><div class="speaker">${a.name}</div><p class="assistant-text">${escapeText(m.text)}</p>${m.result?resultCard():''}</div>`}</div>`).join('')}${state.pending?`<div class="assistant-row"><div class="agent-avatar">${a.face}</div><div class="assistant-body"><p class="assistant-text">正在处理你的补充<span class="streaming-dot"></span></p></div></div>`:''}</div></div><div class="composer-wrap"><div class="composer">${state.quote?'<div class="reply-quote">引用：小鸟示意图.svg<button aria-label="取消引用" data-action="unquote">×</button></div>':''}${chips(state.messageMaterials,true)}<label class="field-label" for="message" hidden>继续补充需求</label><textarea id="message" aria-label="继续补充需求" placeholder="说说你想怎么调整，也可以添加资料…">${escapeText(state.message)}</textarea><div class="composer-tools"><button class="text-button" data-action="materials">＋ 添加资料</button>${primary('发送','send',state.pending?'disabled':'')}</div></div><p class="composer-foot">有想调整的地方，直接在这里说。满意后再验收。</p></div></section>`;}
function acceptPage() {return `<section class="page narrow">${steps(3)}<div class="accept-intro"><div><div class="eyebrow">最后一步</div><h1>这些成果符合你的需求吗？</h1><p class="intro">选定最终成果，满意就完成验收。</p></div></div><div class="summary-box"><div class="caption">需求</div><p>${escapeText(state.requirement||'画一只鸟，配一段简短介绍。')}</p></div><div class="accept-list">${['result','answer','audio'].map(id=>{const file=byId(id);return `<label class="accept-item"><input type="checkbox" data-accept="${id}" ${state.accepted.has(id)?'checked':''} aria-label="将 ${escapeText(file.name)} 作为最终成果">${file.kind==='image'?'<img src="bird.svg" class="accept-thumb" alt="小鸟成果示意">':fileDot(file)}<span class="accept-description"><h3>${escapeText(file.name)}</h3><p>${id==='result'?'本次完成的图片 · 原型示意':id==='answer'?'冻结当前文字内容':'可选音频 · 原型示意'}</p></span><button type="button" class="text-button" data-action="preview" data-file="${id}">预览</button></label>`;}).join('')}</div><div class="accept-note">只验收所选成果。无需先保存到工作空间。</div>${state.error?`<p class="error" role="alert">${escapeText(state.error)}</p>`:''}<div class="accept-footer"><button class="outline-button" data-page="chat">返回继续修改</button>${primary('验收完成','complete')}</div></section>`;}
function donePage() {const ids=state.completed.length?state.completed:['result','answer'];return `<section class="page narrow done-page">${steps(3)}<div class="done-symbol" aria-hidden="true">✓</div><h1>需求已完成</h1><p class="intro">成果已正式交付，随时可以回来查看。</p><div class="done-result">${ids.includes('result')?'<img src="bird.svg" alt="本次验收的小鸟成果示意">':''}<div class="done-result-body">${ids.map(id=>{const file=byId(id);return `<div class="file-row">${fileDot(file)}<div><strong>${escapeText(file.name)}</strong><small>已验收</small></div><button class="text-button" style="margin-left:auto" data-action="preview" data-file="${id}">查看</button></div>`;}).join('')}<div class="done-actions"><button class="outline-button" data-action="download-selected">下载成果</button><button class="light-button" data-action="save-selected">保存到工作空间</button></div></div></div><div class="done-footer"><button class="text-button" data-action="new">提一个新需求 →</button><button class="text-button" data-page="space">查看工作空间</button></div></section>`;}
function spacePage() {const saved=[...state.saved].filter(id=>!files.some(f=>f.id===id));return `<section class="page"><div class="space-head"><div><div class="eyebrow">你的资料与成果</div><h1>工作空间</h1></div><button class="outline-button" data-page="request">提需求</button></div><p class="intro">已有资料与主动保存的内容放在一起，下次可以继续使用。</p><div class="space-list">${[...saved,...files.map(f=>f.id)].map(id=>{const file=byId(id);return `<div class="space-row"><div class="file-row">${fileDot(file)}<div><strong>${escapeText(file.name)}</strong><small>${file.type} · ${file.size}</small></div></div><span class="space-source">${saved.includes(id)?'来自悬赏议事':'已有资料'}</span><button class="text-button" data-action="preview" data-file="${id}">预览</button><button class="text-button" data-action="download" data-file="${id}">下载</button></div>`;}).join('')}</div><p class="agent-note">会话中的内容只有在你选择保存后，才进入这里。</p></section>`;}
const pages={request:requestPage,agents:agentsPage,chat:chatPage,accept:acceptPage,done:donePage,space:spacePage};
function render() {main.innerHTML=pages[state.page]();document.getElementById('breadcrumb-current').textContent=labels[state.page];document.querySelectorAll('[data-page]').forEach(b=>{if(b.closest('.preview-bar'))b.setAttribute('aria-current',b.dataset.page===state.page?'page':'false');});document.querySelectorAll('.side-link').forEach(b=>b.classList.toggle('is-current',state.page==='space'?b.dataset.page==='space':b.dataset.page==='chat'));}
function go(page) { if(!pages[page])return;state.page=page;state.error='';history.replaceState(null,'','#'+page);render();main.scrollTop=0; }
function dialogHeader(title,description='') {return `<div class="dialog-header"><div><h2 id="dialog-title">${title}</h2>${description?`<p>${description}</p>`:''}</div><button type="button" class="close-button" data-action="close" aria-label="关闭">×</button></div>`;}
function showDialog(content) {if(!dialog.open)state.lastFocus=document.activeElement;dialogBody.innerHTML=content;if(!dialog.open)dialog.showModal();}
function openPicker(preserve=false) {if(!preserve){state.pickerTarget=state.page==='chat'?'chat':'request';state.pickerDraft=new Set(state.pickerTarget==='chat'?state.messageMaterials:state.materials);}state.previewFromPicker=false;const all=[...files,...[...state.saved].filter(id=>!files.some(f=>f.id===id)).map(byId)];showDialog(`${dialogHeader('添加资料','从工作空间选择图片、文档、音频等。')}<div class="dialog-content"><p class="picker-label">全部资料</p>${all.map(file=>`<div class="picker-row"><input id="pick-${file.id}" type="checkbox" data-pick="${file.id}" ${state.pickerDraft.has(file.id)?'checked':''} aria-label="选择 ${escapeText(file.name)}"><label for="pick-${file.id}">${fileDot(file)}<span><strong>${escapeText(file.name)}</strong><small>${file.type} · ${file.size}</small></span></label><button type="button" data-action="picker-preview" data-file="${file.id}">预览</button></div>`).join('')}</div><div class="dialog-footer"><button class="text-button" data-action="close">取消</button>${primary('添加（'+state.pickerDraft.size+'）','apply-materials','id="apply-materials"')}</div>`);}
function textContent(id) {return id==='answer'?'小鸟停在枝头，羽毛呈柔和的蓝色。画面以浅色背景衬托它安静而轻盈的姿态。\n\n此文字仅用于交互原型演示。':id==='table'?'名称,类型,用途\n小鸟示意图,图片,画面沟通\n风格说明,文档,要求说明\n声音示意,音频,多媒体展示':'风格说明\n\n希望画面干净、自然。主体是一只停在树枝上的小鸟，背景避免复杂文字。\n\n这些是可选资料，不添加也可以提需求。\n此文件为原型示例。';}
function preview(id,fromPicker=false) {const file=byId(id);state.previewId=id;state.previewFromPicker=fromPicker;let body=file.kind==='image'?'<img class="preview-image" src="bird.svg" alt="小鸟示意图">':file.kind==='audio'?`<div class="preview-audio">${audioMarkup()}<p class="preview-meta">合成示意音，仅用于原型播放控件演示。</p></div>`:`<div class="preview-text">${escapeText(textContent(id))}</div>`;showDialog(`${dialogHeader(escapeText(file.name),file.type+'预览')}<div class="dialog-content">${body}<p class="preview-meta">原型示意内容，不是实际 Agent 交付。</p></div><div class="dialog-footer">${fromPicker?'<button class="text-button" data-action="back-picker">返回选择</button>':saveButton(id,'text-button')}${primary('下载','download',`data-file="${id}"`)}</div>`);}
function closeDialog() {dialog.close();}
function save(id) {state.saved.add(id);toast('已保存到工作空间（原型演示）');render();if(dialog.open&&!state.previewFromPicker)preview(state.previewId,false);}
function download(id) {const file=byId(id);const blob=file.kind==='image'?new Blob([birdSvg],{type:'image/svg+xml'}):file.kind==='audio'?audioBlob:new Blob([textContent(id)],{type:id==='table'?'text/csv;charset=utf-8':'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);}
function resetRequest() {Object.assign(state,{requirement:'',materials:[],message:'',messageMaterials:[],messages:[],quote:false,revision:1,pending:false,completed:[],accepted:new Set(['result','answer'])});go('request');}
let responseTimer;
document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button||button.disabled)return;if(button.dataset.page){go(button.dataset.page);return;}const action=button.dataset.action,id=button.dataset.file;switch(action){case 'new':clearTimeout(responseTimer);resetRequest();break;case 'choose-agent':if(!state.requirement.trim()){state.error='请先描述你的需求。';render();document.getElementById('requirement').focus();}else go('agents');break;case 'select-agent':state.agent=button.dataset.agent;render();break;case 'start':go('chat');break;case 'materials':openPicker();break;case 'apply-materials':if(state.pickerTarget==='chat')state.messageMaterials=[...state.pickerDraft];else state.materials=[...state.pickerDraft];closeDialog();render();break;case 'remove-material':if(state.page==='chat')state.messageMaterials=state.messageMaterials.filter(x=>x!==id);else state.materials=state.materials.filter(x=>x!==id);render();break;case 'picker-preview':preview(id,true);break;case 'preview':event.preventDefault();preview(id);break;case 'back-picker':openPicker(true);break;case 'close':closeDialog();break;case 'save':save(id);break;case 'download':download(id);break;case 'save-selected':for(const value of state.completed.length?state.completed:['result','answer'])state.saved.add(value);toast('所选成果已保存（原型演示）');render();break;case 'download-selected':for(const value of state.completed.length?state.completed:['result','answer'])download(value);break;case 'quote':state.quote=true;render();document.getElementById('message').focus();break;case 'unquote':state.quote=false;render();break;case 'send':{if(!state.message.trim()&&!state.messageMaterials.length){document.getElementById('message').focus();return;}state.messages.push({role:'user',text:state.message,materials:[...state.messageMaterials]});state.message='';state.messageMaterials=[];state.quote=false;state.pending=true;render();document.getElementById('thread').scrollTop=100000;responseTimer=setTimeout(()=>{state.revision++;state.pending=false;state.messages.push({role:'assistant',text:'已收到你的补充，这是新一版示意。原结果仍保留在会话中。',result:true});if(state.page==='chat'){render();document.getElementById('thread').scrollTop=100000;}},600);break;}case 'complete':if(!state.accepted.size){state.error='请至少选择一项最终成果。';render();return;}state.completed=[...state.accepted];go('done');break;}});
document.addEventListener('input',event=>{if(event.target.id==='requirement')state.requirement=event.target.value;if(event.target.id==='message')state.message=event.target.value;});
document.addEventListener('change',event=>{const target=event.target;if(target.dataset.pick){target.checked?state.pickerDraft.add(target.dataset.pick):state.pickerDraft.delete(target.dataset.pick);document.getElementById('apply-materials').textContent='添加（'+state.pickerDraft.size+'）';}if(target.dataset.accept){target.checked?state.accepted.add(target.dataset.accept):state.accepted.delete(target.dataset.accept);}});
dialog.addEventListener('close',()=>{if(state.lastFocus?.isConnected)state.lastFocus.focus();});
dialog.addEventListener('click',event=>{if(event.target===dialog){const rect=dialog.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)closeDialog();}});
window.addEventListener('hashchange',()=>{const page=location.hash.slice(1);if(pages[page])go(page);});
// Valid local WAV placeholder: explicitly not speech, birdsong, or model output.
function makeAudio(){const rate=16000,length=rate*2,buffer=new ArrayBuffer(44+length*2),v=new DataView(buffer);const str=(offset,text)=>{for(let i=0;i<text.length;i++)v.setUint8(offset+i,text.charCodeAt(i));};str(0,'RIFF');v.setUint32(4,36+length*2,true);str(8,'WAVE');str(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,rate,true);v.setUint32(28,rate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);str(36,'data');v.setUint32(40,length*2,true);for(let i=0;i<length;i++){const t=i/rate,envelope=Math.sin(Math.PI*i/length)**2;v.setInt16(44+i*2,Math.sin(t*2*Math.PI*440)*1100*envelope,true);}return new Blob([buffer],{type:'audio/wav'});}
const audioBlob=makeAudio(),audioURL=URL.createObjectURL(audioBlob);window.addEventListener('beforeunload',()=>URL.revokeObjectURL(audioURL));
const initial=location.hash.slice(1);state.page=pages[initial]?initial:'request';render();
